### ISSUE TITLE
have short description for collections page and longer description for detail page

### ISSUE THREAD

**Issue by amzoss** [visualizingthefuture/examples-repository#21]

**Comment by zoews** [comment]
Just to clarify @amzoss, does this short description refer to an entire new metadata field (like "summary" and "full description")? Or limiting what appears on the /dataviz/ and /datasets/ pages within the catalog view to a certain # of characters/words?

**Comment by amzoss** [comment]
That's a good question/point! It's probably easier not to have two separate fields that need to be filled out. If we want to implement this, we could just create a snippet that displays on the gallery view. Right now, though, we're using the original Wax gallery style, which really doesn't show any metadata. That's probably something we need to change, since we'll have non-visual items like datasets.

Net result: I don't think we need to modify the submission system to do this, but I do think this issue might be helpful to remind us to make interface changes.

**Comment by amzoss** [comment]
this is dependent on #76

**Comment by amzoss** [comment]
actually not sure we want to do this. the gallery page is nicest when each example is pretty simple, so might not be enough room for description.

**Comment by amzoss** [comment]
can consider doing this as part of #76, but may decide that's too much clutter. will leave it to other issue to make that decision.
