### ISSUE TITLE
work with website team on name, branding, integrations, etc.

### ISSUE THREAD

**Issue by amzoss** [visualizingthefuture/examples-repository#38]

**Comment by amzoss** [comment]
thinking about something like "Teach Data Viz", which would operate as an umbrella or superset name for all of the resources targeted to teachers (instructional modules, examples, maybe podcast).

**Comment by ejklein** [comment]
- [ ] set up meeting/email thread w/website team to talk about common vision/what we both already have?

**Comment by amzoss** [comment]
web team gave us the go-ahead to do our own branding, no immediate action needed
