### ISSUE TITLE
provide access to high resolution version

### ISSUE THREAD

**Issue by amzoss** [visualizingthefuture/examples-repository#39]
could be that we ask people to submit a high res file through a file upload or ask for link directly to high res version. or data curator could seek out highest resolution version available.

**Comment by amzoss** [comment]
should include a download file link on the item detail page? maybe even on browse page?

**Comment by zoews** [comment]
I believe you solved this in a recent commit @amzoss ? Will close if so

**Comment by amzoss** [comment]
I think we can close this. We have a large image viewer on item page now, and we have another issue for call to action buttons like downloading asset files - #85
