### ISSUE TITLE
Front page design 2.0 - add buttons, call-to-action text?

### ISSUE THREAD

**Issue by zoews** [visualizingthefuture/examples-repository#49]

**Comment by zoews** [comment]
I think at the very least, doing a once-over on all text on the site right now would be helpful. The call for submissions will likely drive some traffic to us. I'll leave this off the project board but assign to myself.

**Comment by amzoss** [comment]
Good call, and thanks! I'm happy to help with this.

I'm a bit unhappy with the current state of the filters, so I'm a bit worried about going public with that, but I think I should probably at least have the latest working version be driving the datasets and datavis browse pages, so I'll try to make that a priority this week.

**Comment by amzoss** [comment]
@zoews should we call this done?
